spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
#oauth:
#  kakao:
#    client-id: ${KAKAO_CLIENT_ID}
#    client-secret: ${KAKAO_CLIENT_SECRET}
#    client-authentication-method: client_secret_post
#    redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
#    authorization-grant-type: authorization_code
#    scope: profile_nickname, profile_image, account_email
#    authorization-uri: https://kauth.kakao.com/oauth/authorize
#    token-uri: https://kauth.kakao.com/oauth/token
#    user-info-uri: https://kapi.kakao.com/v2/user/me
#    user-name-attribute: id